# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Values common to all flavors

# Example variables from UDS package repo template. Update to relevant variables after templating
# imagePullSecrets:
#   - name: "private-registry"

# postgresql:
#   enabled: false
#   postgresqlServer: ###ZARF_VAR_EXAMPLE_DB_ENDPOINT###
#   existingSecret: "example-postgres"
#   existingSecretPasswordKey: "password"
#   postgresqlUsername: ###ZARF_VAR_EXAMPLE_DB_USERNAME###
#   postgresqlDatabase: ###ZARF_VAR_EXAMPLE_DB_NAME###
#   service:
#     port: 5432
