{{- if .Values.default.ipAddressPoolCIDR }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
  {{- if .Values.interface }}
  interfaces:
    - {{ .Values.interface }}
  {{- end }}
{{- end }}
