tasks:
  - name: cluster
    actions:
      - description: Destroy k3d cluster
        cmd: k3d cluster delete uds

  - name: bundle
    actions:
      - description: Remove the Deployed UDS #TEMPLATE_APPLICATION_NAME# Bundle
        cmd: ./uds remove ./bundle/uds-bundle-#TEMPLATE_APPLICATION_NAME#-test*.tar.zst --confirm --no-progress
