# Default values for addresspools.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

default:
  ipAddressPoolCIDR: ""

adminIngress:
  ipAddressPool: ""
  namespace: "istio-admin-gateway"
  matchLabels:
    app: admin-ingressgateway

tenantIngress:
  ipAddressPool: ""
  namespace: "istio-tenant-gateway"
  matchLabels:
    app: tenant-ingressgateway

passthroughIngress:
  ipAddressPool: ""
  namespace: "istio-passthrough-gateway"
  matchLabels:
    app: passthrough-ingressgateway

interface: ""