# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: CI Doc Shim

on:
  pull_request:
    paths:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - adr/**
      - docs/**
      - .gitignore
      - renovate.json
      - releaser.yaml
      - oscal-component.yaml
      - CODEOWNERS
      - LICENSE
      - CONTRIBUTING.md
      - SECURITY.md

jobs:
  validate:
    strategy:
      matrix:
        type: [install, upgrade]
        flavor: [upstream, registry1, unicorn]
    uses: defenseunicorns/uds-common/.github/workflows/callable-ci-docs-shim.yaml@f922776396f05f743055f2751fe19ec0160968ae # v1.7.3
    with:
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
    secrets: inherit # Inherits all secrets from the parent workflow.
