name: CI Doc Shim

on:
  pull_request:
    paths:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - adr/**
      - docs/**
      - .gitignore
      - renovate.json
      - .release-please-config.json
      - release-please-config.json
      - oscal-component.yaml
      - CODEOWNERS
      - LICENSE
      - CONTRIBUTING.md
      - SECURITY.md

jobs:
  validate:
    strategy:
      matrix:
        type: [install, upgrade]
        flavor: [upstream, registry1, unicorn]
    uses: defenseunicorns/uds-common/.github/workflows/callable-ci-docs-shim.yaml@86886015d1edc43036b3dd000fbd972a384beb8f # v1.0.0
    with:
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
    secrets: inherit # Inherits all secrets from the parent workflow.
