# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release

on:
  push:
    branches:
      - main

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write

jobs:
  publish:
    permissions:
      contents: write # Allows writing the content of the repository.
      packages: write # Allows writing the content of the repository's packages.
      id-token: write
    strategy:
      matrix:
        flavor: [upstream, registry1, unicorn]
        architecture: [amd64, arm64]
        exclude:
          - flavor: registry1
            architecture: arm64
    uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@dd9f310a238e555a9ce433a171a2b310f9e49f62 # v1.5.0
    with:
      flavor: ${{ matrix.flavor }}
      runsOn: ${{ matrix.architecture == 'arm64' && 'uds-marketplace-ubuntu-arm64-8-core' || 'uds-marketplace-ubuntu-big-boy-8-core' }}
      uds-releaser: true
    secrets: inherit # Inherits all secrets from the parent workflow.
