name: Scorecards supply-chain security
on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: ["main"]

# Declare default permissions as read only.
permissions: read-all

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-scorecard.yaml@86886015d1edc43036b3dd000fbd972a384beb8f # v1.0.0
