name: Test-Deploy

on:
  workflow_call:
    inputs:
      upgrade-flavors:
        required: true
        type: string
      flavor:
        required: true
        type: string
      type:
        required: true
        type: string

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write

jobs:
  run-test:
    name: deploy
    runs-on: ${{ matrix.architecture == 'arm64' && 'uds-marketplace-ubuntu-arm64-4-core' || 'uds-marketplace-ubuntu-big-boy-4-core' }}
    timeout-minutes: 20
    if: contains(inputs.upgrade-flavors, inputs.flavor) || inputs.type == 'install'

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Clean Runner
        uses: defenseunicorns/uds-common/.github/actions/clean-runner@e3008473beab00b12a94f9fcc7340124338d5c08 # v0.13.1

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@e3008473beab00b12a94f9fcc7340124338d5c08 # v0.13.1
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          chainguardIdentity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test-deploy@e3008473beab00b12a94f9fcc7340124338d5c08 # v0.13.1
        with:
          flavor: ${{ inputs.flavor }}
          type: ${{ inputs.type }}

      - name: UDS Badge Verification
        uses: defenseunicorns/uds-common/.github/actions/verify-badge3008473beab00b12a94f9fcc7340124338d5c08 # v0.13.1

      - name: Debug Output
        if: ${{ always() }}
        uses: defenseunicorns/uds-common/.github/actions/debug-output@e3008473beab00b12a94f9fcc7340124338d5c08 # v0.13.1

      - name: Save logs
        if: ${{ always() }}
        uses: defenseunicorns/uds-common/.github/actions/save-logs@e3008473beab00b12a94f9fcc7340124338d5c08 # v0.13.1
        with:
          suffix: ${{ inputs.type }}-${{ inputs.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
